//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class done_service
    {
        public int ID { get; set; }
        public int service_id { get; set; }
        public int laborant_id { get; set; }
        public System.DateTime date { get; set; }
        public int order_id { get; set; }
    
        public virtual order order { get; set; }
        public virtual service service { get; set; }
        public virtual user user { get; set; }
    }
}
