//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class insurance_bills
    {
        public int ID { get; set; }
        public System.DateTime dateOfBill { get; set; }
        public int insurance_company_id { get; set; }
        public decimal price { get; set; }
        public bool bill_status { get; set; }
        public int buhgalter_id { get; set; }
    
        public virtual insurance_company insurance_company { get; set; }
        public virtual user user { get; set; }
    }
}
