//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lab20Entities : DbContext
    {
        public static lab20Entities _context;
        public static lab20Entities GetContext()
        {
            if (_context == null)
                _context = new lab20Entities();
            return _context;
        }
        public lab20Entities()
            : base("name=lab20Entities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<done_service> done_service { get; set; }
        public virtual DbSet<insurance_bills> insurance_bills { get; set; }
        public virtual DbSet<insurance_company> insurance_company { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<order_status> order_status { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
