//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.done_service = new HashSet<done_service>();
        }
    
        public int ID { get; set; }
        public System.DateTime dateOfOrder { get; set; }
        public string service_ids { get; set; }
        public int status_id { get; set; }
        public int patient_id { get; set; }
        public decimal probirka_BAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<done_service> done_service { get; set; }
        public virtual order_status order_status { get; set; }
        public virtual patient patient { get; set; }
    }
}
